version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: duxcore
      POSTGRES_PASSWORD: 123web123
      POSTGRES_DB: duxcore
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
  duxcore-backend:
    build: ./
    ports:
      - 6969:6969
      - 7418:7418
    depends_on:
      - postgres
