version: "3"
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      duxcore-core:
        condition: service_started

  duxcore-core:
    build: ./
    restart: always
    environment:
      DATABASE_URL: postgres://localhost:123web123@postgres/duxcore
    ports:
      - 40765:40765
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_started
