services:
  pgsql:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: duxcore
      POSTGRES_PASSWORD: 123web123
      POSTGRES_DB: duxcore
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - pgsql