name: Deployment Workflow
on:
  push:
    branches: [dev]
  workflow_dispatch:
jobs:
  npm-publish:
    name: test-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Deployment Script
        uses: duxcore/deploy@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          deployment-url: ${{ secrets.DEPLOY_URL }}
          deployment-secret: ${{ secrets.DEPLOY_SECRET }}
          API_PORT: ${{ secrets.API_PORT }}
          WS_PORT: ${{ secrets.WS_PORT }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
