name: Deployment Pipeline
on:
  release:
    types: [created]
jobs:
  deploy-website:
    name: deploy-website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run Deployment Script
        uses: duxcore/deploy@dev
        with:
          service-id: ${{ secrets.WEBSITE_SERVICE_ID }}
          service-secret: ${{ secrets.WEBSITE_SERVICE_SECRET }}
          deployment-url: ${{ secrets.DEPLOYMENT_URL }}
          api-bearer: ${{ secrets.API_BEARER }}
          api-secret: ${{ secrets.API_SECRET }}
          config: website/.deployment.json
          branch: overhaul
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-master-core:
    name: deploy-master-core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run Deployment Script
        uses: duxcore/deploy@dev
        with:
          service-id: ${{ secrets.CORE_MASTER_SERVICE_ID }}
          service-secret: ${{ secrets.CORE_MASTER_SERVICE_SECRET }}
          deployment-url: ${{ secrets.DEPLOYMENT_URL }}
          api-bearer: ${{ secrets.API_BEARER }}
          api-secret: ${{ secrets.API_SECRET }}
          config: core/.master-deployment.json
          branch: overhaul
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
